### ISSUE TITLE
About pointnet 2

### ISSUE THREAD

**Issue by suetme** [WanquanF/NeuralPoints#21]
After I successfully compiled pointnet2 and installed the dependencies required by the project, this problem： 
Traceback (most recent call last):
  File "train_view_toy.py", line 1, in <module>
    from pointnet2 import pointnet2_utils as pn2_utils
  File "/home/suetme/NeuralPoints-main/model/conpu_v6/pointnet2/pointnet2_utils.py", line 7, in <module>
    import pointnet2_cuda as pointnet2
ImportError: /home/suetme/miniconda3/envs/NePs/lib/python3.8/site-packages/pointnet2-0.0.0-py3.8-linux-x86_64.egg/pointnet2_cuda.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationESs
occurred when executing the train_script101_test.py. I think it may be caused by the mismatch of GCC compilation.So you can tell me the specific environment you use？

**Comment by suetme** [comment]
My usage environment is: GCC 7.5.0, ubuntu18.04, cuda10.02, pythoch1.6, torchvision0.7.0. cudatoolkit10.2,torch-geometric2.1.0.post1
